== Algorithm

[source,java,linenums]
----
include::{source_base_path}/AddTwoNumbers.java[]
----

== Review
https://blog.expo.io/should-we-use-react-native-1465d8b607ac[Should we use React Native?]

这是对 Airbnb 弃用 React Native 的回应。作者写此文的真正动机是什么？作者是 Facebook 早期员工，也是 Quora 联合创始人，最近他的新公司是 Expo.io，一站式的 React Native 开发平台/工具链。本文传递的主要意思是，如果用 React Native，请用 Expo：）

1，如果你开始做一个全新的app并打算几乎100%使用Javascript，用RN；2，如果你已有一个原生的 app，但有几个简单的用webview也能做的页面，如“关于” “设置”，用RN；3，如果你想在原生app里加复杂的页面或重写，别用RN。

== Tip
 写了一篇文章 https://mp.weixin.qq.com/s/1TSWNvhF0pCQn7gxbpCzaw[炎炎夏日沉思] ， 货币政策等 

== share
XX国，资本收益远大于劳动收益。

缺乏权力的制衡，不会放弃印钞机的税赋。长期看还是要通胀。

法令性通胀下，欠债是好事，持有现金会受到巨大的惩罚。

法令性通胀下，对金融投资投机的人非常有益。

尽量把手中的现金转变成相应的资产商品。土地、矿藏、山林水地、房产店铺、古董、家俱、茅台、五粮液... 这些都是财富，都可在适当的时候转换化现金，而且比现金抗通胀能力更高。

离印钞机尽量近一点。 比如选择相应的城市，离印钞机越近越好，北京、上海、省级城市、省会、市、县、乡、村。 比如选择相应的行业，离印钞机越近越好，政府，国企，事业单位，离其近的行业，外贸，最市场化的行业，被 ZF打压的行业。

学习相应的金融经济货币知识，明白相应的规则，学习相应的交易知识,控制相应的风险。

明白了解国内国际相应的投资渠道，进行相应的组合投资，控制风险。

提高自己的资产收益率。不管是用打工，创业、金融、投资或其他，使自己的资产收益率超越通胀率。

从全球来看，不管哪个国家纸币都必然增加通胀的, 乐于从通胀中获利吧。
